version: '3.8'

services:
  web:
    container_name: django_app
    build: .
    command: gunicorn --env DJANGO_SETTINGS_MODULE=API.settings -c python:config.gunicorn_config API.wsgi
    volumes:
      - ./:/code
      # - ./API:/code/API:ro
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=Maamoun
      - DB_PASS=sv_gtab101enter
      - SECRET_KEY=b43bed6bfeb44d4076e3b0ef5d9c10fb23279c71304eb4b180abe34b8bc60e69
      - DEBUG=True
      - WEB_RELOAD=true
    depends_on:
      - db
  
  db: # this name must be the same in DB_HOST
    container_name: db_app
    image: postgis/postgis:16-3.4-alpine
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: Maamoun
      POSTGRES_PASSWORD: sv_gtab101enter
    ports:
      - 5432:5432
  
  # adminer:
  #   image: adminer
  #   container_name: adminer_app
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  postgres-db:
